image: python:3

before_script:
  - pip install tox

stages:
  - test

py34-dj111:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj111

py35-dj111:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj111

py36-dj111:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj111

py34-dj20:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj20

py35-dj20:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj20

py36-dj20:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj20

py37-dj20:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj20

py35-dj21:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj21

py36-dj21:
  image: python:3.6
  stage: test
  script:
    - tox -e py35-dj21

py37-dj21:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj21

flake8:
  stage: test
  script:
    - tox -e flake8

isort:
  stage: test
  script:
    - tox -e isort
